In [1]:
#Importamos las librerias a usar
import numpy as np
import pandas as pd
from scipy import stats
from matplotlib import pyplot
import matplotlib.pyplot as plt
import matplotlib

from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('Pokemon.csv')

In [5]:
df2 = df[['BaseTotal', 'HP', 'Attack', 'Defense', 'Sp.Atk', 'Sp.Def', 'Speed']].copy()

In [49]:
df.columns

Index(['#', 'Name', 'Type1', 'Type2', 'Generation', 'Legendary',
       'TypesStrenght', 'Weak', 'Normal', 'Resist', 'Inmune', 'EvolutionsLeft',
       'BaseTotal', 'HP', 'Attack', 'Defense', 'Sp.Atk', 'Sp.Def', 'Speed',
       'CumSum', 'Male_Ratio', 'Female_Ratio', 'Min_Hind-HP', 'Max_Hind-HP',
       'Min_Hind-Attack', 'Max_Hind-Attack', 'Min_Hind-Defense',
       'Max_Hind-Defense', 'Min_Hind-Sp.Atk', 'Max_Hind-Sp.Atk',
       'Min_Hind-Sp.Def', 'Max_Hind-Sp.Def', 'Min_Hind-Speed',
       'Max_Hind-Speed', 'Min_Neutra-HP', 'Max_Neutra-HP',
       'Min_Neutral-Attack', 'Max_Neutral-Attack', 'Min_Neutral-Defense',
       'Max_Neutral-Defense', 'Min_Neutral-Sp.Atk', 'Max_Neutral-Sp.Atk',
       'Min_Neutral-Sp.Def', 'Max_Neutral-Sp.Def', 'Min_Neutral-Speed',
       'Max_Neutral-Speed', 'Min_Benef-HP', 'Max_Benef-HP', 'Min_Benef-Attack',
       'Max_Benef-Attack', 'Min_Benef-Defense', 'Max_Benef-Defense',
       'Min_Benef-Sp.Atk', 'Max_Benef-Sp.Atk', 'Min_Benef-Sp.Def',
       'Max_Be

In [53]:
TS = df.groupby('Generation')

In [55]:
for key, item in TS:
    print(TS.get_group(key), "\n\n")

       #        Name     Type1    Type2  Generation  Legendary  \
0      1   Bulbasaur     Grass   Poison           1    STARTER   
1      2     Ivysaur     Grass   Poison           1    STARTER   
2      3    Venusaur     Grass   Poison           1    STARTER   
3      4  Charmander      Fire      NaN           1    STARTER   
4      5  Charmeleon      Fire      NaN           1    STARTER   
5      6   Charizard      Fire   Flying           1    STARTER   
6      7    Squirtle     Water      NaN           1    STARTER   
7      8   Wartortle     Water      NaN           1    STARTER   
8      9   Blastoise     Water      NaN           1    STARTER   
9     10    Caterpie       Bug      NaN           1     NORMAL   
10    11     Metapod       Bug      NaN           1     NORMAL   
11    12  Butterfree       Bug   Flying           1     NORMAL   
12    13      Weedle       Bug   Poison           1     NORMAL   
13    14      Kakuna       Bug   Poison           1     NORMAL   
14    15  

In [6]:
df2.head()

BaseTotal  HP  Attack  Defense  Sp.Atk  Sp.Def  Speed
0        318  45      49       49      65      65     45
1        405  60      62       63      80      80     60
2        525  80      82       83     100     100     80
3        309  39      52       43      60      50     65
4        405  58      64       58      80      65     80

In [37]:
X = df2.drop(['BaseTotal'], axis=1)
y = df2['BaseTotal']

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2, random_state=66)

In [39]:
clf_rf = RandomForestRegressor(n_estimators=30)
clf_rf.fit(X_train , y_train)
accuracies = cross_val_score(estimator = clf_rf, X = X_train, y = y_train, cv = 5,verbose = 1)
y_pred = clf_rf.predict(X_test)
print('')
print('###### Random Forest ######')
print('Score : %.4f' % clf_rf.score(X_test, y_test))
print(accuracies)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred)**0.5
r2 = r2_score(y_test, y_pred)

print('')
print('MSE    : %0.2f ' % mse)
print('MAE    : %0.2f ' % mae)
print('RMSE   : %0.2f ' % rmse)
print('R2     : %0.2f ' % r2)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.



###### Random Forest ######
Score : 0.9514
[0.93803771 0.93456051 0.96538755 0.93924084 0.9507775 ]

MSE    : 562.51 
MAE    : 15.28 
RMSE   : 23.72 
R2     : 0.95 


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.2s finished


In [40]:
clf_lr = LinearRegression()
clf_lr.fit(X_train , y_train)
accuracies = cross_val_score(estimator = clf_lr, X = X_train, y = y_train, cv = 5,verbose = 1)
y_pred = clf_lr.predict(X_test)
print('')
print('####### Linear Regression #######')
print('Score : %.4f' % clf_lr.score(X_test, y_test))
print(accuracies)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred)**0.5
r2 = r2_score(y_test, y_pred)

print('')
print('MSE    : %0.2f ' % mse)
print('MAE    : %0.2f ' % mae)
print('RMSE   : %0.2f ' % rmse)
print('R2     : %0.2f ' % r2)


####### Linear Regression #######
Score : 1.0000
[1. 1. 1. 1. 1.]

MSE    : 0.15 
MAE    : 0.03 
RMSE   : 0.39 
R2     : 1.00 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished


In [41]:
clf_ar = AdaBoostRegressor(n_estimators=1000)
clf_ar.fit(X_train , y_train)
accuracies = cross_val_score(estimator = clf_ar, X = X_train, y = y_train, cv = 5,verbose = 1)
y_pred = clf_ar.predict(X_test)
print('')
print('###### AdaBoost Regression ######')
print('Score : %.4f' % clf_ar.score(X_test, y_test))
print(accuracies)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred)**0.5
r2 = r2_score(y_test, y_pred)

print('')
print('MSE    : %0.2f ' % mse)
print('MAE    : %0.2f ' % mae)
print('RMSE   : %0.2f ' % rmse)
print('R2     : %0.2f ' % r2)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.



###### AdaBoost Regression ######
Score : 0.8997
[0.88662805 0.89197496 0.92682478 0.91425333 0.91169533]

MSE    : 1160.05 
MAE    : 27.51 
RMSE   : 34.06 
R2     : 0.90 


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    5.4s finished


In [42]:
clf_gbr = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1,max_depth=1, random_state=0, loss='ls',verbose = 1)
clf_gbr.fit(X_train , y_train)
accuracies = cross_val_score(estimator = clf_gbr, X = X_train, y = y_train, cv = 5,verbose = 1)
y_pred = clf_gbr.predict(X_test)
print('')
print('###### Gradient Boosting Regression #######')
print('Score : %.4f' % clf_gbr.score(X_test, y_test))
print(accuracies)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred)**0.5
r2 = r2_score(y_test, y_pred)

print('')
print('MSE    : %0.2f ' % mse)
print('MAE    : %0.2f ' % mae)
print('RMSE   : %0.2f ' % rmse)
print('R2     : %0.2f ' % r2)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


      Iter       Train Loss   Remaining Time 
         1       11469.5544            0.09s
         2       10538.5972            0.07s
         3        9736.4063            0.06s
         4        9007.5193            0.06s
         5        8337.0518            0.05s
         6        7738.0487            0.05s
         7        7188.9076            0.05s
         8        6716.0116            0.04s
         9        6259.0079            0.04s
        10        5861.1493            0.05s
        20        3333.5533            0.03s
        30        2110.0035            0.02s
        40        1453.5013            0.02s
        50        1057.8283            0.01s
        60         805.1996            0.01s
        70         632.3688            0.01s
        80         510.1787            0.00s
        90         421.3717            0.00s
       100         355.2642            0.00s
      Iter       Train Loss   Remaining Time 
         1       11708.9159            0.03s
        

[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.1s finished


In [43]:
df3 = df2.copy()

In [44]:
df3b = df3.drop('BaseTotal', axis=1)

In [45]:
y_pred=clf_rf.predict(df3b)
y_pred

array([315.2       , 406.46666667, 533.26666667, 309.9       ,
       404.03333333, 528.23333333, 313.7       , 405.43333333,
       527.        , 204.03333333, 202.03333333, 400.43333333,
       205.6       , 203.        , 396.2       , 256.76666667,
       347.2       , 476.13333333, 252.43333333, 406.33333333,
       261.83333333, 444.16666667, 294.23333333, 433.46666667,
       325.1       , 465.16666667, 304.8       , 443.13333333,
       286.36666667, 368.36666667, 499.7       , 281.16666667,
       367.        , 499.03333333, 324.3       , 490.46666667,
       297.8       , 508.36666667, 255.26666667, 430.06666667,
       248.8       , 454.16666667, 331.9       , 397.66666667,
       492.83333333, 290.63333333, 418.1       , 317.03333333,
       452.36666667, 284.16666667, 398.3       , 289.13333333,
       438.5       , 318.43333333, 505.06666667, 305.73333333,
       460.53333333, 334.93333333, 557.7       , 300.23333333,
       390.43333333, 506.73333333, 330.73333333, 411.3 

In [ ]:
df3['randNumCol'] = np.random.randint(1, 6, df1.shape[0])